### ISSUE TITLE
2 get-requests to get all authors

### ISSUE THREAD

**Issue by LisaGotzian** [LisaGotzian/scicloud#39]
[insert cussing here]
Scopus has changed their API, so the default "META" view for [abstract retrieval](https://dev.elsevier.com/guides/AbstractRetrievalViews.htm) doesn't include all authors (only the first one) nor does it include abstracts. Both we need in `3_getScopusMetaData.R`. For these, we'd need institutional API keys which I don't even know how to get.

The only solution we can think of: The authors we can get from a second get-request to [article retrieval](https://dev.elsevier.com/guides/ArticleMetadataViews.htm). We propose to add a new argument to `getScopusMetaData()`, eg a binary `allAuthors` which will then spark a second get-request to the Article Metadata API. We would then explain in the documentation that for this, we'll send two get-requests, it will take twice as long and the quota will be reached quicker.

Please also check what we need in `searchScopus.R` or how the search-API is affected.

**Comment by JJuliusB** [comment]
In order to avoid the two requests approach, another simple way for retrieving all authors as well as the abstracts would be to send the request from a university IP (or use a VPN client, respectively). As our users most probably belong to universities, this should be ok for them, I think.
The full use of `searchScopus.R` requires a connection to the university's intranet anyway.
