### ISSUE TITLE
Error in processMetaDataMatrix: subMatrix[mat_idx]

### ISSUE THREAD

**Issue by JJuliusB** [LisaGotzian/scicloud#41]
Error in subMatrix[mat_idx] : invalid Index type 'list'

**Comment by LisaGotzian** [comment]
We have “café” in our Tf_Idf matrix generated from `processMetaDataMatrix()`. I think `labdsv::indval()` in `calculateModels()` transforms this into a “cafe.“, before, there was no “cafe.”
When I try to get representative papers (lines 354-355), I am calling the Tf_Idf again which doesn’t have “cafe.” in it (because labdsv::indval() made it up). While we could get the representative papers in other ways, it is just a symptom of an issue which we have to see how to deal with.

**Comment by JJuliusB** [comment]
Yeah, maybe you're right. But also, trying different PDFs lead to different errors. Damn....

**Comment by JJuliusB** [comment]
It seems that not only "cafe." is a problem.
Also:
```
[1] "organization." "X.fairtrade."  "respondents."  "cafe."         "farmers."      "members."     
 [7] "producers."    "consumption."  "ajzen."        "individuals."  "sumers."       "universita."  
[13] "X.fair"        "X.true."       "X.astous" 
```

**Comment by JJuliusB** [comment]
I think we should put more effort in preprocessing the words from the fulltext, so that `labdsv::indval()` does not cause trouble. :S

**Comment by JJuliusB** [comment]
Done. Commit `a39431a ` did it totally.
